// app/components/header.tsx
import {changePage} from "~/store/pageStore";
import store from "~/store";

export function Header() {
  return (
    <nav className="flex items-center justify-between p-3 pl-5 bg-elevation-3 rounded-b-2xl">
        <a href="/" className="flex items-center justify-center text-lg">
            <img src="/logo_title.svg" alt="Logo" className="w-52" />
        </a>
        <div className="flex items-center justify-center text-lg">
            <button className="hover:underline" onClick={() => store.dispatch(changePage("MODS"))}>MODS</button>
            <hr className="border-l-1 h-6 rounded-2xl ml-2 mr-2"/>
            <button className="hover:underline" onClick={() => store.dispatch(changePage("TUTORIALS"))}>TUTORIALS</button>
            <hr className="border-l-1 h-6 rounded-2xl ml-2 mr-2"/>
            <button className="hover:underline" onClick={() => store.dispatch(changePage("TOOLS"))}>TOOLS</button>
            <hr className="border-l-1 h-6 rounded-2xl ml-2 mr-2"/>
            <a href="https://discord.gg/3PBUg43y" className="hover:underline">DISCORD</a>
        </div>
    </nav>
  );
}

// src/lib/Header.svelte
<script lang="ts">
    import {env} from "$env/dynamic/public";
</script>

<div class="w-full bg-gray-2 h-20 rounded-b-md shadow-md flex items-center justify-between">
    <a href="/" class="pl-6">
        <h1 class="text-3xl font-bold text-center text-gray-800"><img src="/cotlmod_logo.svg" alt="logo"/> </h1>
    </a>
    <div class="flex flex-row items-center ">
        <a href="/" class="text-2xl font-bold text-center m-4">Mods</a>
        <hr class="stroke-1 w-0.5 h-10 bg-white"/>
        <a href="/tutorials" class="text-2xl font-bold text-center m-4">Tutorials</a>
        <hr class="stroke-1 w-0.5 h-10 bg-white"/>
        <a href="/tools" class="text-2xl font-bold text-center m-4">Tools</a>
        <hr class="stroke-1 w-0.5 h-10 bg-white"/>
        <a href="https://discord.gg/MUjww9ndx2" target="_blank" rel="noreferrer" class="text-2xl font-bold text-center m-4">Discord</a>
    </div>
    <div class="flex flex-row items-center">
        <a href="https://discordapp.com/api/oauth2/authorize?client_id={env.PUBLIC_CLIENT_ID}&scope=identify&response_type=code" class="text-xl font-bold text-center m-4 bg-red rounded-lg p-2">Login</a>
    </div>
</div>

<style>
    a {
        font-family: "Julius Sans One";
    }
</style>
